### ISSUE TITLE
googleUser.grantOfflineAccess is still prompting account chooser

### ISSUE THREAD

**Issue by kishoregunturu** [google/google-api-javascript-client#306]
gapi.auth2.getAuthInstance().currentUser.get().grantOfflineAccess({ 'scope': offlinescopes.join(" ") }).then(function (auth) {
            vm.authResult.code = auth.code;
}

The documentation states that it should skip the account chooser. I am calling the offline access on additional scopes for the current user and it still pops up account chooser. Please advise. I do not want user to login twice.

**Comment by TMSCH** [comment]
Hi @kishoregunturu, could you provide the configuration you pass to the `gapi.auth2.init` call?

You should indeed not see the account chooser, i.e. the screen where you can select which Google Account to use. However, it will show an authorization screen so that the user can authorize the scopes requested, even if the scopes were already authorized upon sign in. This is because a code allows to request Google API's even when the user is no more signed in to your app, and so the user has to consciously authorize this type of access.

**Comment by kishoregunturu** [comment]
Thank you for getting back. Here is my workflow and code
initiated the script tag in the head 
 <script async defer src="https://apis.google.com/js/api.js"
        onload="this.onload=function(){};handleClientLoad()"
        onreadystatechange="if (this.readyState === 'complete') this.onload()"></script>
//the gapi init
 gapi.load('client:auth2', function () {
                gapi.auth2.init({ client_id: window.appConfig.clientId, scope: 'profile email') }).then(function () {
                    });
            });
//button click event
  return gapi.auth2.getAuthInstance().signIn().then(function (resp) {
            vm.updateSigninStatus(resp);
        });
//after authentication user in our app server side
//call offline access. this is where the account chooser keeps popping up instead of consent form
gapi.auth2.getAuthInstance().currentUser.get().grantOfflineAccess({ 'scope': 'https://www.googleapis.com/auth/admin.directory.user.readonly https://www.googleapis.com/auth/admin.directory.orgunit.readonly https://}).then(function(auth){
});

**Comment by kishoregunturu** [comment]
[index.txt](https://github.com/google/google-api-javascript-client/files/1068935/index.txt)
Here is my html file with the set up

**Comment by TMSCH** [comment]
@kishoregunturu thanks for the further information. I indeed see the account chooser screen first, which is a bug. I will investigate and get back to you.

**Comment by kishoregunturu** [comment]
Thank you so much. Please keep me posted. I have deadline for prod release. Any help will be trully appreciated

**Comment by TMSCH** [comment]
@kishoregunturu we deployed a fix that will only display the correct account instead of all logged in Google accounts in the account chooser screen. Let me know if that works for you!

**Comment by kishoregunturu** [comment]
I want to confirm the fix. It will still show the account chooser second time  but only the logged in accounts??

**Comment by TMSCH** [comment]
@kishoregunturu right. I'm currently investigating whether we can skip this screen altogether.

**Comment by sawanttushar** [comment]
I also getting the same screen for already signed in user. Is there any fixed deployed for this issue?

**Comment by TMSCH** [comment]
@sawanttushar not at this time. We're still discussing the behavior.

**Comment by slimCODE** [comment]
Any New Year resolution to fix this flow? ;) It's quite annoying (and confusing) for our users.

**Comment by TMSCH** [comment]
We are working on implementing the behavior but I unfortunately can't provide an ETA.

**Comment by knoxz** [comment]
I think I have the same problem.
In theory, everything is working. I have the user give API access on the first login.

Calling auth2.grantOfflineAccess().then(signInCallback) to send the access token to the server if there is no data for the user on login, prompts another account chooser and will also ask for permissions again.

Here is my code: https://hastebin.com/opuhaconud.xml

Is there any way to avoid this?

**Comment by AbdulShaikh** [comment]
@TMSCH: Is there any update available? I have noticed it's started asking for permissions(consent screen) again and again which is not the case earlier.

**Comment by kongguibin** [comment]
This consent screen is required  on each time an offline code is issued, since, with an offline code, your application has the ability to request data on behalf of the user when the user is not present and in front of your application. User must consent on each such code issued.
https://stackoverflow.com/questions/30637984/what-does-offline-access-in-oauth-mean

**Comment by fkpama** [comment]
Hello,

Any news on this issue?

Thanks

**Comment by dominik-theConstruct** [comment]
Hey Google Guys,
Any news on this? This is very annoying to see all the user accounts on the popup screen ... I'm able to validate the proper account being picked at the backend server but that's very user unfriendly experience.
Thanks,
D

**Comment by cheino** [comment]
This is affecting my customer's project as well and still appears to be unresolved as of today.  Please advise.  Thanks.

**Comment by HerrPeter** [comment]
I understand there may be other problems besides this one that needs fixing, but signing a user in should be a simple and straight forward task at this point with technology. If there is anything I may be able to help with, I'd be happy to do so. 

As it stands, I too am still experiencing this issue along with everyone else.

- Thank you for your time

**Comment by apop94** [comment]
Hi, guys! Any update on this?

**Comment by gpashis** [comment]
@TMSCH @grant Do we have any sample code for getting new access token?

**Comment by cmditch** [comment]
Wondering if there is any update or workaround for this?

Thanks!

**Comment by MathiasGilson** [comment]
Hey guys !
Still having the issue over here
here is my code

```js
 grantOfflineAccess() {
        return new Promise((resolve, reject) => {
                    if (gapi.auth2.getAuthInstance().isSignedIn.get()) {
                        return gapi.auth2
                            .getAuthInstance()
                            .currentUser.get()
                            .grantOfflineAccess({
                                prompt: "consent",
                                scope: "profile email"
                            })
                            .then(response => {
                                if (response && response.code) {
                                    return resolve(response.code)
                                }
                                return reject(Error("no offline access code"))
                            })
                    }
                    return reject(Error("no user"))
        })
    }

```

**Comment by albohlabs** [comment]
> Note that none is not available for the offline code flow.

source: https://developers.google.com/identity/sign-in/web/reference#gapiauth2offlineaccessoptions

**Comment by albohlabs** [comment]
`grantOfflineAccess` signs in the user in and can replace the `signIn` method.
When the authorization code is passed to the callback, the current user can be received to by calling the `getAuthInstance`.

```
gapi.auth2.getAuthInstance()
    .grantOfflineAccess({
      prompt: 'consent'
    })
    // @workaround timing issues with fetching the google profile 
    // which is reading deferred infos from the OAuth2 response
    .then((code) => 
      new Promise<{ code: string }>((res) => {
        window.setTimeout(() => res(code), 1000);
      })
    )
    .then(
      ({ code }) =>
        [
          gapi.auth2.getAuthInstance().currentUser.get(),
          code
        ] as const
    );
```

**Comment by rajivsubra1981** [comment]
@albohlabs Do you check if the refresh token has been received previously for the user logging in - I think in your workaround a new refresh token will be issued on every login

**Comment by albohlabs** [comment]
@rajivsubra1981 This is indeed the case. But for my use case this was not an issue.

**Comment by Joebayld** [comment]
This still seems to be an issue.. @TMSCH Are you still working on this?

**Comment by TMSCH** [comment]
Hi @Joebayld - I am not a maintainer of this library anymore.

**Comment by mykola-zomchak** [comment]
Having the exact same situation as @Joebayld

**Comment by Joebayld** [comment]
I’m wondering if we should open a new issues as the one who was working on this is no longer a maintainer.

**Comment by dvanderb** [comment]
This looks like a question about Google Login and Authentication. Please address this question to the google-signin tag on stackoverflow(https://stackoverflow.com/questions/tagged/google-signin)

If you believe this is in error, please reopen the issue.
