### ISSUE TITLE
window.gapi.auth2.getAuthInstance().signIn doesn't send callback in Chrome

### ISSUE THREAD

**Issue by Serginho** [google/google-api-javascript-client#571]
I tested this with different browsers, operative systems and google accounts. We conclude:

- In Firefox works properly.
- In Chrome Android doesn't work.
- In Chrome Desktop, works on Windows, but not in Linux and Mac.

When code fails  is because `window.gapi.auth2.getAuthInstance().signIn` callback is not called after google login window/tab is closed.

It seems the client library isn't able to communicate with the window/tab.

**Comment by SergeMakDev** [comment]
We have the same problem on Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36

.signIn({prompt: 'consent'}).then(function() {...}) doesn't call the code in .then() block after google login window is closed.

**Comment by steveetm** [comment]
Run this code in console before pressing your login button:
`window.addEventListener('message',(...args)=>console.log(args))`

You may see some relevant errors in the console afterwards.

**Comment by Serginho** [comment]
@steveetm Yes 3 event from dpi iframe.

`"{"method":"fireIdpEvent","params":{"type":"sessionSelectorChanged","newValue":{"hint":...`
`"{"method":"fireIdpEvent","params":{"type":"authResult","clientId":...`
`"{"id":"xxx-xxxxxxxxxxx","result":{"error":"user_logged_out"},"rpcToken":...`

**Comment by SergeMakDev** [comment]
Our further research showed that the problem has been fixed starting the build 79.0.3945.36

**Comment by Serginho** [comment]
@SergeMakDev In Chrome Canary 80.0.3966.0's still not working.

**Comment by Serginho** [comment]
@grant Maybe could you please give us some additional information about this? We don't know if this issue will be fixed quickly or we have to apply a hotfix using OAuth 2  REST api.

**Comment by jordan-thoms** [comment]
We're seeing this issue also. As it seems like a Chrome bug, has anyone reported it on the chromium bug tracker yet? I did some searching but couldn't find it.

**Comment by Serginho** [comment]
@jordan-thoms No we didn't report it cause we are not sure if it's actually a chrome bug, we know it doesn't work in chrome, but... what's the problem? the library is obfuscated so it's impossible to debug. We can't report a bug that we don't know what the bug is.

**Comment by jordan-thoms** [comment]
I've reported this at https://bugs.chromium.org/p/chromium/issues/detail?id=1024992 now, please add any additional information there and star the bug. It seems most likely that it's a Chrome issue as it is platform specific and worked in earlier versions.

**Comment by steveetm** [comment]
It is a duplicate of #561 .
Just try to disable same-site cookies in chrome, and it will work. Check that thread and the report date.

**Comment by steveetm** [comment]
In a chrome thread I was told make sure that all third-party apis ready for this. And the third(?:D)-party api in this case is google-apis. Honestly, I don't know what is going on.

**Comment by jordan-thoms** [comment]
@steveetm Yeah you're right, disabling the flag fixes it. So the inconsistent behaviour here will just be depending on if you have the flag on/off as they are doing a partial rollout. I'm assuming Google will make sure this doesn't hit stable without at least updating their own services to be compatible!

**Comment by Serginho** [comment]
Any update on this? The problem still exists

**Comment by iisa** [comment]
Hello,

I am experiencing the same issue with not having the resolve callback fire after calling `.signIn(options)` --
I tested this with different browsers on Mac:

- firefox can reach this resolve callback (83.0 (64-bit))
- chrome desktop can only reach the error callback intermittently (87.0.4280.67 (Official Build) (x86_64))
- chrome mobile can reach the resolve callback (87.0.4280.66)
- safari can reach resolve callback (Version 14.0 (14610.1.28.1.10))

I've looked at the related issues around this promise not resolving properly, is there any update to chrome desktop experience?

I tried to circumvent the whole thing by using the `signIn2.render` button generator, but the success callback on load will fire too early, sometimes.

thanks in advance, looking forward to hearing from you.  Best, Isa

**Comment by felixmeziere** [comment]
I have this exact same issue, still in mid-2021. On chrome for ios (only), the signin promise does not resolve most of the time (but sometimes it does). It works on all other platforms/browsers.

**Comment by felixmeziere** [comment]
> @steveetm Yes 3 event from dpi iframe.
> 
> `"{"method":"fireIdpEvent","params":{"type":"sessionSelectorChanged","newValue":{"hint":...`
> `"{"method":"fireIdpEvent","params":{"type":"authResult","clientId":...`
> `"{"id":"xxx-xxxxxxxxxxx","result":{"error":"user_logged_out"},"rpcToken":...`
> 
> In firefox works properly and send 4 messages.

More specifically, I have this exact same probleme, with `sessionSelectorChanged` and "error":"user_logged_out"

**Comment by ariccio** [comment]
> More specifically, I have this exact same probleme, with `sessionSelectorChanged` and "error":"user_logged_out"

I've was investigating this same problem yesterday, seeing the same `user_logged_out` error, and I was able to trace that to some weird issues with magic strings missing in cookies:
https://github.com/anthonyjgrove/react-google-login/issues/451#issuecomment-858148763

**Comment by ariccio** [comment]
In my case, it was on an android device.

**Comment by ariccio** [comment]
x-ref: https://github.com/google/google-api-javascript-client/issues/367

**Comment by dvanderb** [comment]
This looks like a question about Google Login and Authentication. Please address this question to the google-signin tag on stackoverflow(https://stackoverflow.com/questions/tagged/google-signin)

If you believe this is in error, please reopen the issue.
