### ISSUE TITLE
Businesscommunications discovery doc getting a 404 

### ISSUE THREAD

**Issue by KatamariJr** [google/google-api-javascript-client#801]
When using `gapi` with a discovery doc for the Google Business Communications API (which is specified in the docs as `https://businesscommunications.googleapis.com/$discovery/rest`, visible in any web browser ), I get a 404 in the js setup code and cannot use any of the `gapi.client.businesscommunications` functions. It seems that gapi is rewriting this request to use `https://content-businesscommunications.googleapis.com/static/proxy.html`, which is returning a 404 to the request, preventing it from adding the client.

A discovery doc that works as expected is `https://people.googleapis.com/$discovery/rest`, which redirects via `gapi` to `https://content-people.googleapis.com/static/proxy.html`, which does not have a 404 and works as expected.

**Comment by dvanderb** [comment]
This has been fixed and should be working properly now. Thanks for reporting the issue.

**Comment by KatamariJr** [comment]
Hey @dvanderb , I'm still getting that same 404 in my console when trying to use this API.

**Comment by dvanderb** [comment]
Sorry about this I am following up.

**Comment by washamdev** [comment]
Sorry to have to ask, but is there any ETA on this fix going live? Like are we talking 1 week vs 1 month vs 1 year even? Thank you!

**Comment by nikuliak** [comment]
Please use standalone NodeJS API examples as a workaround while we are working on the fix: https://developers.google.com/business-communications/business-messages/resources/samples

**Comment by khussain-cars** [comment]
I've got API code running on GMB API v4.9 right now that needs to transition to the Account Management API v1 before the sunset date (2022-04-30). I'm getting this same error trying to use the new API.

Do we know if this fix will be rolled out in time, AND/OR will the sunset date be delayed, since the new API isn't working?

Thanks

**Comment by nikuliak** [comment]
We have submitted a fix today and are expecting a push next week.

**Comment by ph1lb4** [comment]
Any update on the ETA?

**Comment by nikuliak** [comment]
I believe this is fixed: https://content-businesscommunications.googleapis.com/static/proxy.html is served with 200 OK.
