### ISSUE TITLE
idpiframe_initialization_failed, R

### ISSUE THREAD

**Issue by fterrag** [google/google-api-javascript-client#812]
Hi there,

We have a few customers who are receiving this error when trying to sign in using Google:

```
Uncaught {error: 'idpiframe_initialization_failed', details: 'R'}
```

What does R mean?

Thanks!

**Comment by reves** [comment]
Would like to mention, that I get the same error, but only in incognito mode.

**Comment by ccdunder** [comment]
The `details` should probably be `Cookies are not enabled in current environment`. A fix has been submitted and should roll out next week.

**Comment by s-nikhil** [comment]
> The `details` should probably be `Cookies are not enabled in current environment`. A fix has been submitted and should roll out next week.

Any updates here @ccdunder ? Still facing same issue

**Comment by suryasudeepb17** [comment]
> Hi there,
> 
> We have a few customers who are receiving this error when trying to sign in using Google:
> 
> ```
> Uncaught {error: 'idpiframe_initialization_failed', details: 'R'}
> ```
> 
> What does R mean?
> 
> Thanks!

I am facing the same problem bro
has your problem was resolved or not?
if it is resolved plz help me out

**Comment by s-nikhil** [comment]
This problem has been now resolved and it's showing proper error now


Nikhil Singh

**Comment by suryasudeepb17** [comment]
Thanks for your response
But i am still facing the same problem
It's showing popup_closed_by_user
Any solution regarding this?
After clicking sign and selecting account its not displaying anything [may
be onsign function was not called]
Please help me out

**Comment by ccdunder** [comment]
@suryasudeepb17 This is unrelated to this issue. For help with authentication issues please post questions on Stack Overflow with the google-oauth tag.
